### ISSUE TITLE
indexes

### ISSUE THREAD

**Issue by ioRekz** [kbastani/neo4j-dbpedia-importer#1]
What would you suggest to create indexes on title property for example ? 
You can also suggest me that the question does not make sense and that's not the way to go

**Comment by kbastani** [comment]
Run this Cypher query: 

```
CREATE INDEX ON :Page(title)
```

The index will take 10 minutes or so to compile. It will only provide performance benefits if you exact match on the title's text. Partial matches using RegEx will not provide a benefit.
